### ISSUE TITLE
Incorrect comment for POSTGRES_HOST line

### ISSUE THREAD

**Issue by juliusiv** [actions/example-services#4]
I believe the comment about why we're using `POSTGRES_HOST=localhost` [here](https://github.com/actions/example-services/blob/dfd84e0637dda63c0359a07a7161fbfd2a6da738/.github/workflows/postgres-service.yml#L65-L67) is incorrect. It appears to be copy-pasta from [these lines](https://github.com/actions/example-services/blob/dfd84e0637dda63c0359a07a7161fbfd2a6da738/.github/workflows/postgres-service.yml#L37-L39). Additionally, in both comments, `container` is misspelled as `contaienr`.

**Comment by juliusiv** [comment]
Also, not necessarily related to the specific problem mentioned in this issue, but I don't really understand the difference between `container-job` and `vm-job` in this example workflow. The main difference I see is that the former has a `container` section which then seems to affect the host and port but it's not clear why exactly we're doing that. I feel like a comment could be warranted, or the existing comment could at least be expanded on. Something along the lines of "Specifying a `container` runs this job in a Docker container. Otherwise, the job runs in a VM outside of a Docker container.", which is what I'm assuming happens?

**Comment by sarahabd** [comment]
Hi @juliusiv, 
the difference is that the first case `container-job` it run the steps on the container and the other `vm-job` run the steps directly on the vm you set on the `runs-on`. 

I think it depends of what you want to do, if you have to run a job in a specific container and avoid to setup the image of the container directly on the vm, it can be useful.

Hope my answer will help !

**Comment by chrispat** [comment]
I have updated the comments in the example.
