### ISSUE TITLE
github actions fail when redis tries to save an RDB snapshot

### ISSUE THREAD

**Issue by brysgo** [actions/example-services#7]
reproduced in PR #6 

not sure what the solution to this, but I'm guessing most CI jobs don't need to persist their redis data

**Comment by brysgo** [comment]
I'll save people the scrolling on the failing build:
```
/__w/example-services/example-services/redis/node_modules/redis/lib/utils.js:112
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

Would be nice if the default redis service for github actions didn't try and save an RDB snapshot.

**Comment by chrispat** [comment]
This is not specific to GitHub Actions as we do not do any configuration of REDIS.  The example here simply launches the container that is on dockerhub.  A quick search shows a few different options but none of them seem to be straight forward.

**Comment by brysgo** [comment]
I'm working around this by re-configuring Redis from the client, I went to dockerhub to see if I can find a way to report issues on the docker image and people in the comments are complaining that the redis image has a trojan: https://hub.docker.com/_/redis/?tab=reviews

Do we know if this is fake news?

**Comment by chrispat** [comment]
i don't know any specific details about that issue with Redis.

**Comment by fergusleahytab** [comment]
Turns out if you override the entrypoint to redis-server it runs without issue. It looks like it was due to a permissions issue, due to running as root - which the redis-server entrypoint handles for.

```

redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

```
